name: Server Build & Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yarn
        run: npm install -g yarn
      - name: Build App
        run: yarn install && yarn run build:prod
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR ./dist/site-frontend/browser ../build
          tar -cvf deploy.tar ../build/

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "deploy.tar"
          target: "/site-frontend"
      
      - name: unpack build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /site-frontend
            rm -rf build
            tar -xvf deploy.tar
            