name: Server Build & Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yarn
        run: npm install -g yarn
      - name: Build App
        run: yarn install && yarn run build:prod
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/site-frontend
          remote: /
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}